COUNTRY_LANGUAGES = {
    'Asia': {
        '🇮🇳 India': [
            ('English', 'en'),
            ('Hindi', 'hi'),
            ('Malayalam', 'ml'),
            ('Tamil', 'ta'),
            ('Telugu', 'te'),
            ('Kannada', 'kn'),
            ('Bengali', 'bn'),
            ('Marathi', 'mr'),
            ('Gujarati', 'gu'),
            ('Punjabi', 'pa'),
            ('Urdu', 'ur'),
        ],
        '🇦🇫 Afghanistan': [('Pashto', 'ps'), ('Dari', 'prs')],
        '🇧🇩 Bangladesh': [('Bengali', 'bn'), ('English', 'en')],
        '🇧🇹 Bhutan': [('Dzongkha', 'dz'), ('English', 'en')],
        '🇧🇳 Brunei': [('Malay', 'ms'), ('English', 'en')],
        '🇰🇭 Cambodia': [('Khmer', 'km')],
        '🇨🇳 China': [('Chinese (Mandarin)', 'zh')],
        '🇮🇩 Indonesia': [('Indonesian', 'id')],
        '🇮🇷 Iran': [('Persian', 'fa')],
        '🇮🇶 Iraq': [('Arabic', 'ar'), ('Kurdish', 'ku')],
        '🇮🇱 Israel': [('Hebrew', 'he'), ('Arabic', 'ar')],
        '🇯🇵 Japan': [('Japanese', 'ja')],
        '🇯🇴 Jordan': [('Arabic', 'ar')],
        '🇰🇿 Kazakhstan': [('Kazakh', 'kk'), ('Russian', 'ru')],
        '🇰🇼 Kuwait': [('Arabic', 'ar'), ('English', 'en')],
        '🇰🇬 Kyrgyzstan': [('Kyrgyz', 'ky'), ('Russian', 'ru')],
        '🇱🇦 Laos': [('Lao', 'lo')],
        '🇱🇧 Lebanon': [('Arabic', 'ar'), ('French', 'fr'), ('English', 'en')],
        '🇲🇾 Malaysia': [
            ('Malay', 'ms'),
            ('English', 'en'),
            ('Chinese', 'zh'),
            ('Tamil', 'ta'),
        ],
        '🇲🇻 Maldives': [('Dhivehi', 'dv'), ('English', 'en')],
        '🇲🇳 Mongolia': [('Mongolian', 'mn')],
        '🇲🇲 Myanmar': [('Burmese', 'my')],
        '🇳🇵 Nepal': [('Nepali', 'ne'), ('English', 'en')],
        '🇰🇵 North Korea': [('Korean', 'ko')],
        '🇴🇲 Oman': [('Arabic', 'ar'), ('English', 'en')],
        '🇵🇰 Pakistan': [
            ('Urdu', 'ur'),
            ('English', 'en'),
            ('Punjabi', 'pa'),
            ('Sindhi', 'sd'),
            ('Pashto', 'ps'),
        ],
        '🇵🇸 Palestine': [('Arabic', 'ar')],
        '🇶🇦 Qatar': [('Arabic', 'ar'), ('English', 'en')],
        '🇸🇦 Saudi Arabia': [('Arabic', 'ar')],
        '🇸🇬 Singapore': [
            ('English', 'en'),
            ('Malay', 'ms'),
            ('Mandarin', 'zh'),
            ('Tamil', 'ta'),
        ],
        '🇰🇷 South Korea': [('Korean', 'ko')],
        '🇱🇰 Sri Lanka': [
            ('Sinhala', 'si'),
            ('Tamil', 'ta'),
            ('English', 'en'),
        ],
        '🇸🇾 Syria': [('Arabic', 'ar')],
        '🇹🇯 Tajikistan': [('Tajik', 'tg'), ('Russian', 'ru')],
        '🇹🇼 Taiwan': [('Chinese (Mandarin)', 'zh')],
        '🇹🇭 Thailand': [('Thai', 'th')],
        '🇹🇱 Timor-Leste': [('Tetum', 'tet'), ('Portuguese', 'pt')],
        '🇹🇷 Türkiye': [('Turkish', 'tr')],
        '🇹🇲 Turkmenistan': [('Turkmen', 'tk')],
        '🇦🇪 United Arab Emirates': [('Arabic', 'ar'), ('English', 'en')],
        '🇺🇿 Uzbekistan': [('Uzbek', 'uz'), ('Russian', 'ru')],
        '🇻🇳 Vietnam': [('Vietnamese', 'vi')],
        '🇾🇪 Yemen': [('Arabic', 'ar')],
    },
    'Europe': {
        '🇦🇱 Albania': [('Albanian', 'sq')],
        '🇦🇩 Andorra': [('Catalan', 'ca')],
        '🇦🇹 Austria': [('German', 'de')],
        '🇧🇾 Belarus': [('Belarusian', 'be'), ('Russian', 'ru')],
        '🇧🇪 Belgium': [('Dutch', 'nl'), ('French', 'fr'), ('German', 'de')],
        '🇧🇬 Bulgaria': [('Bulgarian', 'bg')],
        '🇭🇷 Croatia': [('Croatian', 'hr')],
        '🇨🇾 Cyprus': [('Greek', 'el'), ('Turkish', 'tr')],
        '🇨🇿 Czechia': [('Czech', 'cs')],
        '🇩🇰 Denmark': [('Danish', 'da')],
        '🇪🇪 Estonia': [('Estonian', 'et')],
        '🇫🇮 Finland': [('Finnish', 'fi'), ('Swedish', 'sv')],
        '🇫🇷 France': [('French', 'fr')],
        '🇩🇪 Germany': [('German', 'de')],
        '🇬🇷 Greece': [('Greek', 'el')],
        '🇭🇺 Hungary': [('Hungarian', 'hu')],
        '🇮🇸 Iceland': [('Icelandic', 'is')],
        '🇮🇪 Ireland': [('English', 'en'), ('Irish', 'ga')],
        '🇮🇹 Italy': [('Italian', 'it')],
        '🇱🇻 Latvia': [('Latvian', 'lv')],
        '🇱🇮 Liechtenstein': [('German', 'de')],
        '🇱🇹 Lithuania': [('Lithuanian', 'lt')],
        '🇱🇺 Luxembourg': [
            ('Luxembourgish', 'lb'),
            ('French', 'fr'),
            ('German', 'de'),
        ],
        '🇲🇹 Malta': [('Maltese', 'mt'), ('English', 'en')],
        '🇲🇩 Moldova': [('Romanian', 'ro'), ('Russian', 'ru')],
        '🇲🇨 Monaco': [('French', 'fr')],
        '🇲🇪 Montenegro': [('Montenegrin', 'sr')],
        '🇳🇱 Netherlands': [('Dutch', 'nl')],
        '🇳🇴 Norway': [('Norwegian', 'no')],
        '🇵🇱 Poland': [('Polish', 'pl')],
        '🇵🇹 Portugal': [('Portuguese', 'pt')],
        '🇷🇴 Romania': [('Romanian', 'ro')],
        '🇷🇺 Russia': [('Russian', 'ru')],
        '🇸🇲 San Marino': [('Italian', 'it')],
        '🇷🇸 Serbia': [('Serbian', 'sr')],
        '🇸🇰 Slovakia': [('Slovak', 'sk')],
        '🇸🇮 Slovenia': [('Slovenian', 'sl')],
        '🇪🇸 Spain': [
            ('Spanish', 'es'),
            ('Catalan', 'ca'),
            ('Basque', 'eu'),
            ('Galician', 'gl'),
        ],
        '🇸🇪 Sweden': [('Swedish', 'sv')],
        '🇨🇭 Switzerland': [
            ('German', 'de'),
            ('French', 'fr'),
            ('Italian', 'it'),
            ('Romansh', 'rm'),
        ],
        '🇺🇦 Ukraine': [('Ukrainian', 'uk')],
        '🇬🇧 United Kingdom': [
            ('English', 'en'),
            ('Welsh', 'cy'),
            ('Scottish Gaelic', 'gd'),
        ],
        '🇻🇦 Vatican City': [('Italian', 'it'), ('Latin', 'la')],
        '🇽🇰 Kosovo': [('Albanian', 'sq'), ('Serbian', 'sr')],
    },
    'Africa': {
        '🇩🇿 Algeria': [('Arabic', 'ar'), ('French', 'fr')],
        '🇦🇴 Angola': [('Portuguese', 'pt')],
        '🇧🇯 Benin': [('French', 'fr')],
        '🇧🇼 Botswana': [('English', 'en')],
        '🇧🇫 Burkina Faso': [('French', 'fr')],
        '🇧🇮 Burundi': [('Kirundi', 'rn'), ('French', 'fr'), ('English', 'en')],
        '🇨🇻 Cabo Verde': [('Portuguese', 'pt')],
        '🇨🇲 Cameroon': [('French', 'fr'), ('English', 'en')],
        '🇨🇫 Central African Republic': [('French', 'fr')],
        '🇹🇩 Chad': [('French', 'fr'), ('Arabic', 'ar')],
        '🇰🇲 Comoros': [('Arabic', 'ar'), ('French', 'fr')],
        '🇨🇬 Congo': [('French', 'fr')],
        '🇨🇩 DR Congo': [('French', 'fr')],
        '🇨🇮 Côte d’Ivoire': [('French', 'fr')],
        '🇩🇯 Djibouti': [('Arabic', 'ar'), ('French', 'fr')],
        '🇪🇬 Egypt': [('Arabic', 'ar')],
        '🇬🇶 Equatorial Guinea': [
            ('Spanish', 'es'),
            ('French', 'fr'),
            ('Portuguese', 'pt'),
        ],
        '🇪🇷 Eritrea': [('Tigrinya', 'ti'), ('Arabic', 'ar'), ('English', 'en')],
        '🇸🇿 Eswatini': [('Swazi', 'ss'), ('English', 'en')],
        '🇪🇹 Ethiopia': [('Amharic', 'am'), ('Oromo', 'om'), ('English', 'en')],
        '🇬🇦 Gabon': [('French', 'fr')],
        '🇬🇲 Gambia': [('English', 'en')],
        '🇬🇭 Ghana': [('English', 'en')],
        '🇬🇳 Guinea': [('French', 'fr')],
        '🇬🇼 Guinea-Bissau': [('Portuguese', 'pt')],
        '🇰🇪 Kenya': [('English', 'en'), ('Swahili', 'sw')],
        '🇱🇸 Lesotho': [('Sesotho', 'st'), ('English', 'en')],
        '🇱🇷 Liberia': [('English', 'en')],
        '🇱🇾 Libya': [('Arabic', 'ar')],
        '🇲🇬 Madagascar': [('Malagasy', 'mg'), ('French', 'fr')],
        '🇲🇼 Malawi': [('English', 'en'), ('Chichewa', 'ny')],
        '🇲🇱 Mali': [('French', 'fr')],
        '🇲🇷 Mauritania': [('Arabic', 'ar'), ('French', 'fr')],
        '🇲🇺 Mauritius': [('English', 'en'), ('French', 'fr')],
        '🇲🇦 Morocco': [('Arabic', 'ar'), ('French', 'fr')],
        '🇲🇿 Mozambique': [('Portuguese', 'pt')],
        '🇳🇦 Namibia': [('English', 'en'), ('Afrikaans', 'af')],
        '🇳🇪 Niger': [('French', 'fr')],
        '🇳🇬 Nigeria': [
            ('English', 'en'),
            ('Hausa', 'ha'),
            ('Yoruba', 'yo'),
            ('Igbo', 'ig'),
        ],
        '🇷🇼 Rwanda': [
            ('Kinyarwanda', 'rw'),
            ('English', 'en'),
            ('French', 'fr'),
            ('Swahili', 'sw'),
        ],
        '🇸🇹 São Tomé and Príncipe': [('Portuguese', 'pt')],
        '🇸🇳 Senegal': [('French', 'fr')],
        '🇸🇨 Seychelles': [('English', 'en'), ('French', 'fr')],
        '🇸🇱 Sierra Leone': [('English', 'en')],
        '🇸🇴 Somalia': [('Somali', 'so'), ('Arabic', 'ar')],
        '🇿🇦 South Africa': [
            ('English', 'en'),
            ('Afrikaans', 'af'),
            ('Zulu', 'zu'),
            ('Xhosa', 'xh'),
        ],
        '🇸🇸 South Sudan': [('English', 'en')],
        '🇸🇩 Sudan': [('Arabic', 'ar'), ('English', 'en')],
        '🇹🇿 Tanzania': [('Swahili', 'sw'), ('English', 'en')],
        '🇹🇬 Togo': [('French', 'fr')],
        '🇹🇳 Tunisia': [('Arabic', 'ar'), ('French', 'fr')],
        '🇺🇬 Uganda': [('English', 'en'), ('Swahili', 'sw')],
        '🇿🇲 Zambia': [('English', 'en')],
        '🇿🇼 Zimbabwe': [('English', 'en')],
    },
    'Americas': {
        '🇦🇬 Antigua and Barbuda': [('English', 'en')],
        '🇦🇷 Argentina': [('Spanish', 'es')],
        '🇧🇸 Bahamas': [('English', 'en')],
        '🇧🇧 Barbados': [('English', 'en')],
        '🇧🇿 Belize': [('English', 'en'), ('Spanish', 'es')],
        '🇧🇴 Bolivia': [('Spanish', 'es')],
        '🇧🇷 Brazil': [('Portuguese', 'pt')],
        '🇨🇦 Canada': [('English', 'en'), ('French', 'fr')],
        '🇨🇱 Chile': [('Spanish', 'es')],
        '🇨🇴 Colombia': [('Spanish', 'es')],
        '🇨🇷 Costa Rica': [('Spanish', 'es')],
        '🇨🇺 Cuba': [('Spanish', 'es')],
        '🇩🇲 Dominica': [('English', 'en')],
        '🇩🇴 Dominican Republic': [('Spanish', 'es')],
        '🇪🇨 Ecuador': [('Spanish', 'es')],
        '🇸🇻 El Salvador': [('Spanish', 'es')],
        '🇬🇩 Grenada': [('English', 'en')],
        '🇬🇹 Guatemala': [('Spanish', 'es')],
        '🇬🇾 Guyana': [('English', 'en')],
        '🇭🇹 Haiti': [('Haitian Creole', 'ht'), ('French', 'fr')],
        '🇭🇳 Honduras': [('Spanish', 'es')],
        '🇯🇲 Jamaica': [('English', 'en')],
        '🇲🇽 Mexico': [('Spanish', 'es')],
        '🇳🇮 Nicaragua': [('Spanish', 'es')],
        '🇵🇦 Panama': [('Spanish', 'es')],
        '🇵🇾 Paraguay': [('Spanish', 'es')],
        '🇵🇪 Peru': [('Spanish', 'es')],
        '🇰🇳 Saint Kitts and Nevis': [('English', 'en')],
        '🇱🇨 Saint Lucia': [('English', 'en')],
        '🇻🇨 Saint Vincent and the Grenadines': [('English', 'en')],
        '🇸🇷 Suriname': [('Dutch', 'nl')],
        '🇹🇹 Trinidad and Tobago': [('English', 'en')],
        '🇺🇸 United States': [('English', 'en'), ('Spanish', 'es')],
        '🇺🇾 Uruguay': [('Spanish', 'es')],
        '🇻🇪 Venezuela': [('Spanish', 'es')],
    },
    'Oceania': {
        '🇦🇺 Australia': [('English', 'en')],
        '🇫🇯 Fiji': [('English', 'en')],
        '🇰🇮 Kiribati': [('English', 'en')],
        '🇲🇭 Marshall Islands': [('English', 'en')],
        '🇫🇲 Micronesia': [('English', 'en')],
        '🇳🇷 Nauru': [('English', 'en')],
        '🇳🇿 New Zealand': [('English', 'en')],
        '🇵🇬 Papua New Guinea': [('English', 'en')],
        '🇵🇼 Palau': [('English', 'en')],
        '🇼🇸 Samoa': [('English', 'en')],
        '🇸🇧 Solomon Islands': [('English', 'en')],
        '🇹🇴 Tonga': [('English', 'en')],
        '🇹🇻 Tuvalu': [('English', 'en')],
        '🇻🇺 Vanuatu': [('English', 'en'), ('French', 'fr')],
    },
}
